name: Vercel Wait for Deployment
description:  Wait for a Vercel deployment to finish
author: tj-actions
inputs:
  token:
    description: 'Vercel token can be obtained from https://vercel.com/account/tokens'
    required: true
  project-id:
    description: 'Vercel project id can be obtained from `https://vercel.com/<team>/<project>/settings`'
    required: true
  team-id:
    description: 'Vercel team id can be obtained from `https://vercel.com/teams/<team>/settings`'
    required: false
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: "600"
  delay:
    description: 'Delay in seconds'
    required: false
    default: "5"
  sha:
    description: 'The commit sha to wait for'
    required: true

outputs:
  deployment-id:
    description: 'The deployment id'
    value: ${{ steps.vercel-wait.outputs.id }}
  deployment-url:
    description: 'The deployment url'
    value: ${{ steps.vercel-wait.outputs.url }}
  deployment-state:
    description: 'The deployment state'
    value: ${{ steps.vercel-wait.outputs.state }}
  deployment-alias-error:
    description: 'The deployment alias error'
    value: ${{ steps.vercel-wait.outputs.alias_error }}

runs:
  using: 'composite'
  steps:
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: vercel-wait
      shell: bash
      env:
        # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PROJECT_ID: ${{ inputs.project-id }}
        INPUT_TEAM_ID: ${{ inputs.team-id }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_DELAY: ${{ inputs.delay }}
        INPUT_SHA: ${{ inputs.sha }}
branding:
  icon: clock
  color: white
